Django_RequsetSyatem/Django_RequsetSyatem/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings
from Login import views
from RequstAnswer import views as RequstAnswerViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.WebHome),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('mod/', views.ModUser, name="ModUser"),
    path('home/', views.HomePage, name="HomePage"),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('Notice.urls', namespace='notice')),
    path('captcha', include('captcha.urls')),
    path('RequstAnswer/', include(('RequstAnswer.urls', 'RequstAnswer'), namespace='RequstAnswer')),
    path('Comment/', include(('Comment.urls', 'Comment'), namespace='Comment')),
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    path('Upload/', RequstAnswerViews.Upload),
    path('', views.WebHome),

]

Django_RequsetSyatem/Notice/urls.py
from django.urls import path
from . import views


app_name = 'Notice'


urlpatterns = [
    path('list/', views.CommentNoticeList, name='list'),
    path('update/', views.CommentNoticeUpdate, name='update'),
]

Django_RequsetSyatem/RequstAnswer/urls.py
from django.urls import path,re_path
from . import views

urlpatterns = [
    path('new/', views.CreateNew, name="CreateNew"),
    path('index/', views.Index, name="Index"),
    path('sub/', views.SubIndex, name="SubIndex"),
    path('sub/<str:project>/', views.SubDetail, name='SubDetail'),
    path('sub/<str:project>/check/', views.CheckProject, name='CheckProject'),
    path('sub/<str:project>/reject/', views.RejectProject, name='RejectProject'),
    path('<str:project>/', views.SubDetail, name='Detail'),
    path('<str:project>/del/', views.Del, name='Del'),
    path('', views.Index, name="Index"),
]

Django_RequsetSyatem/RequstAnswer/models.py
from django.db import models

# Create your models here.

class RequestInfo(models.Model):
    RequestNumber = models.AutoField(primary_key=True)
    RequestType = models.CharField(max_length=32,choices=(('RNAseq','RNAseq'), ('scRNAseq', 'scRNAseq'), ('ChIPseq', 'ChIPseq'), ('ATACseq', 'ATACseq'), ('MetaGenmics', 'MetaGenmics'), ('外显子测序', '外显子测序'), ('皮肤遗传解读', '皮肤遗传解读'), ('其他', '其他'),), default='RNAseq')
    RequestUser = models.CharField(max_length=10)
    RequestUserName = models.CharField(max_length=10)
    RequestEmail = models.CharField(max_length=256)
    RequestDate = models.DateTimeField(auto_now_add=True)
    RequestTarget = models.CharField(max_length=10)
    RequestContent = models.TextField(verbose_name='预约内容', blank=True)
    RequestTargetData = models.CharField(max_length=40)
    RequestTargetGroup = models.CharField(max_length=128)
    RequestStatus = models.CharField(max_length=32,choices=(('已提交, 待接受','已预约, 待接受'), ('已提交, 已接受', '已提交, 已接受'), ('已提交, 拒绝','已预约, 拒绝')), default='已提交, 待接受')

class RequestTargetInfo(models.Model):
    TargetName = models.CharField(max_length=10)
    TargetData = models.CharField(max_length=10)
    TargetTrueDate = models.DateField(auto_now_add=False)
    TargetStatus = models.CharField(max_length=32,choices=(('已预约','已预约'), ('未预约', '未预约'),), default='未预约')

Django_RequsetSyatem/RequstAnswer/forms.py
from django import forms
from django.forms import ModelForm
from . import models


class NewRequest(ModelForm):
    class Meta:
        model = models.RequestInfo
        fields = ['RequestType', 'RequestTargetGroup', 'RequestContent', 'RequestTargetData', 'RequestUserName', 'RequestEmail']
    RequestType = forms.ChoiceField(label='咨询类型', choices=(('RNAseq','RNAseq'), ('scRNAseq', 'scRNAseq'), ('ChIPseq', 'ChIPseq'), ('ATACseq', 'ATACseq'), ('MetaGenmics', 'MetaGenmics'), ('外显子测序', '外显子测序'), ('皮肤遗传解读', '皮肤遗传解读'), ('其他', '其他'),), required=True)
    RequestTargetGroup = forms.CharField(label='课题组', max_length=20)
    RequestTargetData = forms.ChoiceField(label='咨询时间', required=True)
    RequestUserName = forms.CharField(label='预约人员', max_length=10)
    RequestEmail = forms.CharField(label='邮箱', max_length=20)

    def __init__(self, *args, **kwargs):
        super(NewRequest, self).__init__(*args, **kwargs)
        self.fields['RequestTargetData'].choices = models.RequestTargetInfo.objects.exclude(TargetStatus='已预约').values_list('TargetData', 'TargetData')

Django_RequsetSyatem/RequstAnswer/views.py
import os
import time
import json
from django.shortcuts import render,redirect,HttpResponse
from . import models
from .forms import NewRequest
from Login.models import LoginUser
from Comment.models import Comment
from Comment.forms import CommentForm
from django.utils import timezone
from notifications.signals import notify

# Create your views here.

def GetCTL(request):
    user = request.session['user_name']
    if LoginUser.objects.get(username=user).info_right == 'admin':
        CTL = 'admin'
    else:
        CTL = 'normal'
    return CTL

def CreateNew(request):
    isactive = 'new'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    user = request.session['user_name']
    CTL = GetCTL(request)
    if request.method == "POST":
        NewRequestForm = NewRequest(request.POST)
        message = "请检查输入！"
        if NewRequestForm.is_valid():
            RequestType = NewRequestForm.cleaned_data['RequestType']
            RequestContent = NewRequestForm.cleaned_data['RequestContent']
            RequestTargetData = NewRequestForm.cleaned_data['RequestTargetData']
            RequestEmail = NewRequestForm.cleaned_data['RequestEmail']
            RequestUserName = NewRequestForm.cleaned_data['RequestUserName']
            RequestTargetGroup = NewRequestForm.cleaned_data['RequestTargetGroup']
            new_requset = models.RequestInfo()
            new_requset.RequestUser = user
            new_requset.RequestEmail = RequestEmail
            new_requset.RequestContent = RequestContent
            new_requset.RequestTargetData = RequestTargetData
            new_requset.RequestTarget = models.RequestTargetInfo.objects.get(TargetData=RequestTargetData).TargetName
            new_requset.RequestType = RequestType
            new_requset.RequestUserName = RequestUserName
            new_requset.RequestTargetGroup = RequestTargetGroup
            new_requset.RequestStatus = '已提交, 待接受'
            new_requset.save()
            notify.send(
                LoginUser.objects.get(username=user),
                recipient=LoginUser.objects.get(username=models.RequestTargetInfo.objects.get(TargetData=RequestTargetData).TargetName),
                verb='提交了预约',
                target=new_requset
            )
            RequestTargetInfoModel = models.RequestTargetInfo.objects.get(TargetData=RequestTargetData)
            RequestTargetInfoModel.TargetStatus = '已预约'
            RequestTargetInfoModel.save()
            return redirect('/RequstAnswer/index/')
        return render(request, 'RequstAnswer/new.html', locals())
    NewRequestForm = NewRequest()
    return render(request, 'RequstAnswer/new.html', locals())

def Index(request):
    isactive = 'Requestinfor'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    data_list = []
    user = request.session['user_name']
    CTL = GetCTL(request)
    list_ob = models.RequestInfo.objects.order_by('RequestTargetData').filter(RequestUser=user)
    for data_info in list_ob:
        data_list.append({
            '预约编号':data_info.RequestNumber,
            '项目类型':data_info.RequestType,
            '预约时间':data_info.RequestTargetData,
            '发起预约时间':data_info.RequestDate.strftime('%Y-%m-%d %H:%M'),
            '预约人员':data_info.RequestUserName,
            '预约状态':data_info.RequestStatus,
        })
    data_dic = {}
    data_dic['userrequest'] = data_list
    data_dic['CTL'] = CTL
    return render(request, 'RequstAnswer/index.html', data_dic,)

def Detail(request, project):
    isactive = 'Requestinfor'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    CTL = GetCTL(request)
    Project_model = models.RequestInfo.objects.get(RequestNumber=project)
    RequestNumber = Project_model.RequestNumber
    RequestType = Project_model.RequestType
#    RequestUser = Project_model.RequestUser
    RequestContent = Project_model.RequestContent
    RequestDate = Project_model.RequestDate.strftime('%Y-%m-%d %H:%M')
    RequestTargetData = Project_model.RequestTargetData
    RequestStatus = Project_model.RequestStatus
    return render(request, 'RequstAnswer/detail.html', locals())

def Del(request, project):
    isactive = 'Requestinfor'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    Project_model = models.RequestInfo.objects.get(RequestNumber=project)
    user = Project_model.RequestUser
    notify.send(
        LoginUser.objects.get(username=user),
        recipient=LoginUser.objects.get(username=models.RequestTargetInfo.objects.get(TargetData=Project_model.RequestTargetData).TargetName),
        verb='删除了预约',
        target=Project_model,
    )
    RequestTargetData = Project_model.RequestTargetData
    RequestTargetInfoModel = models.RequestTargetInfo.objects.get(TargetData=RequestTargetData)
    RequestTargetInfoModel.TargetStatus = '未预约'
    RequestTargetInfoModel.save()
    Project_model.delete()
    return Index(request)

def SubIndex(request):
    isactive = 'sub'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    user = request.session['user_name']
    CTL = GetCTL(request)
    list_project_model = models.RequestInfo.objects.order_by('RequestStatus').filter(RequestTarget=user)
    data_list = []
    for data_info in list_project_model:
        data_list.append({
            '预约编号':data_info.RequestNumber,
            '项目类型':data_info.RequestType,
            '预约时间':data_info.RequestTargetData,
            '预约人员':data_info.RequestUserName,
            '课题组':data_info.RequestTargetGroup,
            '预约状态':data_info.RequestStatus,
        })
    data_dic = {}
    data_dic['userrequest'] = data_list
    data_dic['CTL'] = CTL
    return render(request, 'RequstAnswer/subindex.html', data_dic)

def SubDetail(request, project):
    isactive = 'sub'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    CTL = GetCTL(request)
    Project_model = models.RequestInfo.objects.get(RequestNumber=project)
    RequestNumber = Project_model.RequestNumber
    RequestType = Project_model.RequestType
    RequestUser = Project_model.RequestUser
    RequestTargetGroup = Project_model.RequestTargetGroup
    RequestUserName = Project_model.RequestUserName
    RequestEmail = Project_model.RequestEmail
    RequestContent = Project_model.RequestContent
    RequestTargetData = Project_model.RequestTargetData
    RequestStatus = Project_model.RequestStatus
    RequestDate = Project_model.RequestDate.strftime('%Y-%m-%d %H:%M')
    comments = Comment.objects.filter(Project=project)
    comment_form = CommentForm()
    return render(request, 'RequstAnswer/subdetail.html', locals())

def CheckProject(request, project):
    isactive = 'sub'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    Project_model = models.RequestInfo.objects.get(RequestNumber=project)
    user = request.session['user_name']
    notify.send(
        LoginUser.objects.get(username=user),
        recipient=LoginUser.objects.get(username=Project_model.RequestUser),
        verb='确认了预约',
        target=Project_model,
    )
    Project_model.RequestStatus = '已提交, 已接受'
    Project_model.save()
    return SubIndex(request)

def RejectProject(request, project):
    isactive = 'sub'
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    Project_model = models.RequestInfo.objects.get(RequestNumber=project)
    user = request.session['user_name']
    notify.send(
        LoginUser.objects.get(username=user),
        recipient=LoginUser.objects.get(username=Project_model.RequestUser),
        verb='拒绝了预约',
        target=Project_model,
    )
    Project_model.RequestStatus = '已提交, 拒绝'
    Project_model.save()
    RequestTargetData = Project_model.RequestTargetData
    RequestTargetInfoModel = models.RequestTargetInfo.objects.get(TargetData=RequestTargetData)
    RequestTargetInfoModel.TargetStatus = '未预约'
    RequestTargetInfoModel.save()
    return SubIndex(request)

def Upload(request):
    file_obj = request.FILES.get('UploadFile')
    file_type = request.GET.get('dir')
    file_obj.name = '{}{}'.format(time.time(), file_obj.name)
    file_dir = 'media{}{}'.format(os.sep, file_type)
    if not os.path.exists(file_dir):
        os.makedirs(file_dir)
    file_path = os.path.join("media", file_type, file_obj.name)
    with open(file_path, 'wb') as f:
        for line in file_obj:
            f.write(line)
    dic = {'error': 0, 'url': '/media/{}/{}'.format(file_type, file_obj.name), 'message': '出现内部错误'}
    return HttpResponse(json.dumps(dic))

Django_RequsetSyatem/RequstAnswer/templates/RequstAnswer/detail.html
{% extends "base.html" %}
{% load staticfiles %}



{% block content %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            {% csrf_token %}
            <h2 class="text-center">预约内容</h2>
            <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModal">删除</button>
            <table class="table table-hover row">
                <thead class="thead-light w-100">
                    <tr class="row">
                        <th class="col-4">类别</th>
                        <th class="col-8">内容</th>
                    </tr>
                </thead>
                <tbody class="w-100">
                <tr class="row">
                    <th class="col-4">预约编号</th>
                    <th class="col-8">{{ RequestNumber | safe}}</th>
                </tr>
                <tr class="row">
                    <th class="col-4">项目类型</th>
                    <th class="col-8">{{ RequestType | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-4">项目内容</th>
                    <th class="col-8">{{ RequestContent | safe}}</th>
                </tr>
                <tr class="row">
                    <th class="col-4">预约时间</th>
                    <th class="col-8">{{ RequestTargetData | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-4">发起预约时间</th>
                    <th class="col-8">{{ RequestDate | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-4">预约状态</th>
                    <th class="col-8">{{ RequestStatus | safe }}</th>
                </tr>
                </tbody>
            </table>
        </div>
    </div>
    <div class="modal fade" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">警告</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    真的要删除{{ project }}的数据吗？？？
                </div>
                <div class="modal-footer">
                    <a href="/RequstAnswer/{{ project }}/del/" class="btn btn-danger" role="button">确定</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
                        
{% endblock %}

Django_RequsetSyatem/RequstAnswer/templates/RequstAnswer/index.html
{% extends "base.html" %}
{% load staticfiles %}

{% block css %}
  <link rel="stylesheet" href="{% static 'plugins/DataTables/DataTables-1.10.21/css/jquery.dataTables.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/DataTables/Buttons-1.6.2/css/buttons.dataTables.min.css' %}">
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h2 class="text-center">我的预约</h2>
            <table id="PrevData" class="display" style="width: 100%">
                <thead>
                <tr>
                    <th class="text-center">预约编号</th>
                    <th class="text-center">项目类型</th>
                    <th class="text-center">预约时间</th>
                    <th class="text-center">发起预约时间</th>
                    <th class="text-center">预约人员</th>
                    <th class="text-center">预约状态</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
{% endblock %}
{% block js %}
  <script src="{% static 'plugins/DataTables/DataTables-1.10.21/js/jquery.dataTables.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/Buttons-1.6.2/js/dataTables.buttons.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/Buttons-1.6.2/js/buttons.flash.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/Buttons-1.6.2/js/buttons.html5.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/Buttons-1.6.2/js/buttons.print.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/JSZip-2.5.0/jszip.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/pdfmake-0.1.36/pdfmake.min.js' %}"></script>
  <script src="{% static 'plugins/DataTables/pdfmake-0.1.36/vfs_fonts.js' %}"></script>
  <script type="text/javascript">
          $('#PrevData').DataTable({
              "pagingType": "simple_numbers",
              searching: true,
              destroy : true,
              stateSave: true,
              data: {{ userrequest | safe }},
              'columns': [
              {'data': '预约编号',
                  'render': function (data){
                      return '<a href="/RequstAnswer/'+data+'/">'+'NPSX'+data+'</a>'}},
              {'data': '项目类型'},
              {'data': '预约时间'},
              {'data': '发起预约时间'},
              {'data': '预约人员'},
              {'data': '预约状态'},
              ],
              'language': {
                  'url': '//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Chinese.json'
              },
              dom: 'Bfrtip',
              button: ['copy', 'csv', 'excel', 'pdf', 'print'],
          })
  </script>
{% endblock %}

Django_RequsetSyatem/RequstAnswer/templates/RequstAnswer/new.html
{% extends "base.html" %}
{% load staticfiles %}



{% block content %}
    <div class="row">
        <div class="col-md-6 offset-md-2">
            <form class='form-login' action="/RequstAnswer/new/" method="post" enctype="multipart/form-data">
                {% if message %}
                    <div class="alert alert-warning">{{ message }}</div>
                {% endif %}
                {% csrf_token %}
                <h2 class="text-center">新建预约</h2>
                {{ NewRequestForm.as_p }}
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script src="{% static 'plugins/kindeditor/kindeditor-all.js' %}"></script>
    <script type="text/javascript">
        KindEditor.ready(function(K) {
            window.editor = K.create('#id_RequestContent',{
                width:"100%",
                height:"300",
                resizeType:0,
                uploadJson: '/Upload/',
                filePostName:'UploadFile',
                extraFileUploadParams:{
                    csrfmiddlewaretoken:$("[name='csrfmiddlewaretoken']").val()
                },
                items:[ 'source', '|', 'undo', 'redo', '|', 'preview', 'print', 'template', 'code', 'cut', 'copy', 'paste',
                        'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
                        'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
                        'superscript', 'clearhtml', 'quickformat', 'selectall', '|', 'fullscreen', '/',
                        'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
                        'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat',
                '|', 'image', 'multiimage','media', 'insertfile', 'table', 'hr', 'emoticons', ]
            });
        });
    </script>
{% endblock %}

Django_RequsetSyatem/RequstAnswer/templates/RequstAnswer/subdetail.html
{% extends "base.html" %}
{% load staticfiles %}
{% load mptt_tags %}


{% block content %}
    <div class="row">
        <div class="col-md-8 offset-md-2">
            {% if message %}
                <div class="alert alert-warning">{{ message }}</div>
            {% endif %}
            {% csrf_token %}
            <h2 class="text-center">请求内容</h2>
            {% if CTL == 'admin' %}
                {% if RequestStatus == "已提交, 待接受" %}
                <button type="button" class="btn btn-default pull-left" data-toggle="modal" data-target="#myModalA">接受</button>
                <button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-target="#myModalR">拒绝</button>
                </br>
                {% endif %}
            {% elif CTL == 'normal' and RequestStatus == "已提交, 待接受" %}
                <button type="button" class="btn btn-danger" data-toggle="modal" data-target="#myModalD">删除</button>
            {% endif %}

            <table class="table table-hover row">
                <tbody class="w-100">
                <tr class="row">
                    <th class="col-2">预约编号</th>
                    <th class="col-6">NPSX{{ RequestNumber | safe}}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">项目类型</th>
                    <th class="col-6">{{ RequestType | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">课题组</th>
                    <th class="col-6">{{ RequestTargetGroup | safe}}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">预约人员</th>
                    <th class="col-6">{{ RequestUserName | safe}}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">预约邮箱</th>
                    <th class="col-6">{{ RequestUserName | safe}}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">预约时间</th>
                    <th class="col-6">{{ RequestTargetData | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">发起预约时间</th>
                    <th class="col-6">{{ RequestDate | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">预约状态</th>
                    <th class="col-6">{{ RequestStatus | safe }}</th>
                </tr>
                <tr class="row">
                    <th class="col-2">项目内容</th>
                    <th class="col-6">{{ RequestContent | safe}}</th>
                </tr>
                </tbody>
            </table>
           
            {% if not comments.count %}
            <div>
                <form action="/Comment/post-comment/{{ project }}/" method="POST">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="body">
                            <strong>
                                评论:
                            </strong>
                        </label>
                        <div>
                            {{ comment_form.media }}
                            {{ comment_form.body }}
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary ">发送</button>
                </form>
            </div>
            <br>
            {% else %}
            <label for="body">
                <strong>
                    评论:
                </strong>
            </label>
            {% endif %}
            <div class="row">
                {% recursetree comments %}
                    {% with comment=node %}
                    <div class="{% if comment.reply_to %} offset-1 col-11 {% else %} col-12 {% endif %}">
                        <hr>
                        <p>
                        <strong style="color: pink">
                            {{ comment.user }}
                        </strong>
                        {% if comment.reply_to %}
                            <i class="far fa-arrow-alt-circle-right" style="color: cornflowerblue;"></i>
                            <strong style="color: pink">
                                {{ comment.reply_to }}
                            </strong>
                        {% endif %}
                        </p>
                        <div>{{ comment.body|safe }}</div>
                        <div>
                            <span style="color: gray">
                                {{ comment.created|date:"Y-m-d H:i" }}
                            </span>

                            {% if request.session.is_login %}
                            <button type="button"
                                    class="btn btn-light btn-sm text-muted" 
                                    onclick="load_modal({{ project }}, {{ comment.id }})">
                                回复
                            </button>
                            {% else %}
                            <a class="btn btn-light btn-sm text-muted" 
                               href="/login/">
                                回复
                            </a>
                            {% endif %}
                        </div>

                        <div class="modal fade" 
                             id="comment_{{ comment.id }}" 
                             tabindex="-1"
                             role="dialog"
                             aria-labelledby="CommentModalCenter"
                             aria-hidden="true"
                             >
                             <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
                                 <div class="modal-content" style="height: 480px">
                                     <div class="modal-header">
                                         <h5 class="modal-title" id="exampleModalCenterTitle">回复 {{ comment.user }}：</h5>
                                     </div>
                                     <div class="modal-body" id="modal_body_{{ comment.id }}"></div>
                                 </div>
                             </div>
                        </div>

                        {% if not comment.is_leaf_node %}
                        <div class="children">
                            {{ children }}
                        </div>
                        {% endif %}
                    </div>
                    {% endwith %}
                    {% endrecursetree %}
            </div>

        </div>
    </div>
    <div class="modal fade" id="myModalA">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">警告</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    真的要接受NPSX{{ project }}的预约吗？？？
                </div>
                <div class="modal-footer">
                    <a href="/RequstAnswer/sub/{{ project }}/check/" class="btn btn-danger" role="button">确定</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModalR">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">警告</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    真的要拒绝NPSX{{ project }}的预约吗？？？
                </div>
                <div class="modal-footer">
                    <a href="/RequstAnswer/sub/{{ project }}/reject/" class="btn btn-danger" role="button">拒绝</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModalD">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">警告</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    真的要删除NPSX{{ project }}的数据吗？？？
                </div>
                <div class="modal-footer">
                    <a href="/RequstAnswer/{{ project }}/del/" class="btn btn-danger" role="button">确定</a>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">关闭</button>
                </div>
            </div>
        </div>
    </div>
                        
{% endblock %}

{% block js %}
    <script>
        function load_modal(project, comment_id) {
            let modal_body = '#modal_body_' + comment_id;
            let modal_id = '#comment_' + comment_id;
            if ($(modal_body).children().length === 0) {
                let content = '<iframe src="/Comment/post-comment/' + 
                    project + '/' + comment_id + '/"' + 
                    ' frameborder="0" style="width: 100%; height: 100%;" id="iframe_' + 
                    comment_id +
                    '"></iframe>';
                $(modal_body).append(content);
            };
            $(modal_id).modal('show');
        }
    </script>
{% endblock js %}