Django_RequsetSyatem/Django_RequsetSyatem/urls.py
import notifications.urls
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings
from Login import views
from RequstAnswer import views as RequstAnswerViews

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.WebHome),
    path('login/', views.login),
    path('register/', views.register),
    path('logout/', views.logout),
    path('mod/', views.ModUser, name="ModUser"),
    path('home/', views.HomePage, name="HomePage"),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),
    path('notice/', include('Notice.urls', namespace='notice')),
    path('captcha', include('captcha.urls')),
    path('RequstAnswer/', include(('RequstAnswer.urls', 'RequstAnswer'), namespace='RequstAnswer')),
    path('Comment/', include(('Comment.urls', 'Comment'), namespace='Comment')),
    re_path(r"media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
    path('Upload/', RequstAnswerViews.Upload),
    path('', views.WebHome),

]

Django_RequsetSyatem/Notice/urls.py
from django.urls import path
from . import views


app_name = 'Notice'


urlpatterns = [
    path('list/', views.CommentNoticeList, name='list'),
    path('update/', views.CommentNoticeUpdate, name='update'),
]

Django_RequsetSyatem/Notice/models.py
from django.db import models

# Create your models here.

Django_RequsetSyatem/Notice/views.py
from django.shortcuts import render,redirect
#from Report.models import ReportsInfo
from Login.models import LoginUser

# Create your views here.

def GetCTL(request):
    user = request.session['user_name']
    if LoginUser.objects.get(username=user).info_right == 'admin':
        CTL = 'admin'
    else:
        CTL = 'normal'
    return CTL

def CommentNoticeList(request):
    isactive = ''
    user = request.session['user_name']
    CTL = GetCTL(request)
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    notices = LoginUser.objects.get(username=user).notifications.unread()
    return render(request, 'notice/list.html', locals())


def CommentNoticeUpdate(request):
    isactive = ''
    user = request.session['user_name']
    CTL = GetCTL(request)
    if request.session.get('is_login') == None:
        return render(request, 'LoginWarning.html', locals())
    notice_id = request.GET.get('notice_id')
    if notice_id:
#        report = ReportsInfo.objects.get(ReportNumber=request.GET.get('ReportNumber'))
        pass
    else:
        LoginUser.objects.get(username=user).notifications.mark_all_as_read()
        return render(request, 'notice/list.html', locals())

Django_RequsetSyatem/Notice/templates/notice/list.html
{% extends "base.html" %}
{% load staticfiles %}


{% block content %}
<div class="row">
    <div class="col-md-8 offset-md-2">

    <div class="row mt-4 ml-4">
        <a href="{% url "notice:update" %}" class="btn btn-warning" role="button">清空所有通知</a>
    </div>
    <!-- 未读通知列表 -->
    <div class="row mt-2 ml-4">
        <ul class="list-group">
            {% for notice in notices %}
                <li class="list-group-item" id="notice_link">
                    <span style="color: #01a252;">{{ notice.actor }}</span>
                    {{ notice.verb }}
                    <a href="/RequstAnswer/sub/{{ notice.target.RequestNumber }}/">
                    <span style="color: #5897fb;">
                        NPSX{{ notice.target.RequestNumber }}.
                    </span>
                    </a>
                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ notice.timestamp|date:"Y/m/d H:i" }}
                </li>
            {% endfor %}
        </ul>
    </div>
</div>
</div>
<style>
    #notice_link a:link {
        color: black;
    }

    #notice_link a:visited {
        color: lightgrey;
    }
</style>
{% endblock content %}